### ISSUE TITLE
Split into jaguar_http_cli and jaguar_http

### ISSUE THREAD

**Issue by winterDroid** [Jaguar-dart/jaguar_http#3]
To be able to use the project with flutter it would be helpful to split the project into the generator and core. Otherwise build_runner prevents from adding it to a flutter project (it seems).

I guess this was also the motivation for doing so with jaguar_serializers.

**Comment by tejainece** [comment]
Will fix this.

Meanwhile, you could also try https://github.com/Jaguar-dart/jaguar_client.

It is vanilla cross-platform http package but with support for automatic serialization.

**Comment by winterDroid** [comment]
Great! Thanks. I splitted it already on my own and upgraded some libs in case you want to use that.

**Comment by lejard-h** [comment]
@winterDroid if you need it right now, you can do a pull request, I will review it. I won't be able to work on it before next week.

**Comment by tejainece** [comment]
Created a repository for jaguar_http CLI: https://github.com/Jaguar-dart/jaguar_http_cli
